language: python
python:
 - "3.6"
cache: pip
before_install:
 - easy_install distribute
install:
 - pip install -r requirements.txt
 - pip install random
 - pip install enum
script:
 - python GAME.py
