language: python
python:
 - "3.6"
cache: pip
before_install:
 - easy_install distribute
install:
 - pip install pycodestyle
 - pip install -r requirements.txt
script:
 - pycodestyle GAME.py
 - python GAME.py < commands.txt
